name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Lint and Analyze Code
        run: |
          npm run lint
          npm run analyze

      - name: Build and Test
        run: |
          npm run build
          npm test

      - name: Generate Code Coverage
        run: npm run coverage

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        run: |
          # Replace with your staging deployment command

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && success()
        run: |
          # Replace with your production deployment command

      - name: Notify Team
        if: success()
        run: |
          echo "Deployment successful! Notifying team..."
